### ISSUE TITLE
Contract class

### ISSUE THREAD

**Issue by suntehnik** [jakenjarvis/Android-OrmLiteContentProvider#17]
The documentation says @Contract annotation will automatically create contract class.
How to use contract class with MatcherController? Or I missing some factors?

**Comment by jakenjarvis** [comment]
Hi @suntehnik,
There are a few things you should check.
- Did you add a ormlite-content-provider-compiler to dependency?
- Did you set APT to run properly to build runtime?

Because there here is a sample using ormlite-content-provider-compiler, please check.
- ormlite-content-provider-compiler-sample
  
  https://github.com/jakenjarvis/Android-OrmLiteContentProvider/tree/master/ormlite-content-provider-compiler-sample

**Comment by suntehnik** [comment]
Hi, got it. It's better to create a Contract myself. Thanks for answer and sorry for stupid question.
